//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Superheroes.EF.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.CourseCharacters = new HashSet<CourseCharacter>();
        }
    
        public int CharID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Race { get; set; }
        public string Occupation { get; set; }
        public string AbilityOne { get; set; }
        public string AbilityTwo { get; set; }
        public string AbilityThree { get; set; }
        public string Image { get; set; }
        public int AlignID { get; set; }
    
        public virtual Alignment Alignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCharacter> CourseCharacters { get; set; }
    }
}
