//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Superheroes.EF.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCharacter
    {
        public int CourseCharacterID { get; set; }
        public int CharID { get; set; }
        public int CourseID { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Course Cours { get; set; }
    }
}
